import { Movie, Game, Question, GameOptions } from ".";

export const generateGame = (arr: Movie[], gameOptions: GameOptions) => {
  const game: Game = {
    questions: [],
    ...gameOptions,
  };
  let i = 0;
  while (i < arr.length) {
    let options: Movie[] = [];
    let j = 0;
    while (j < 4) {
      options.push(arr[i + j]);
      j++;
    }
    i += j;
    game.questions.push(<Question>{
      answer: options[~~(Math.random() * options.length)],
      options,
      userAnswer: null,
    });
    options = [];
  }

  return game;
};

export const testData = [
  {
    adult: false,
    backdrop_path: "/27ZkYMWynuK2qiDP6awc3MsCaOs.jpg",
    genre_ids: [10749, 18],
    id: 527641,
    original_language: "en",
    original_title: "Five Feet Apart",
    overview:
      "Seventeen-year-old Stella spends most of her time in the hospital as a cystic fibrosis patient. Her life is full of routines, boundaries and self-control — all of which get put to the test when she meets Will, an impossibly charming teen who has the same illness. There's an instant flirtation, though restrictions dictate that they must maintain a safe distance between them. As their connection intensifies, so does the temptation to throw the rules out the window and embrace that attraction.",
    popularity: 51.401,
    poster_path: "/kreTuJBkUjVWePRfhHZuYfhNE1T.jpg",
    release_date: "2019-03-14",
    title: "Five Feet Apart",
    video: false,
    vote_average: 8.269,
    vote_count: 5419,
  },
  {
    adult: false,
    backdrop_path: "/76LpPdXtCf4WxWDagVT2YcF4e9g.jpg",
    genre_ids: [10752, 28, 18, 36],
    id: 530915,
    original_language: "en",
    original_title: "1917",
    overview:
      "At the height of the First World War, two young British soldiers must cross enemy territory and deliver a message that will stop a deadly attack on hundreds of soldiers.",
    popularity: 65.708,
    poster_path: "/iZf0KyrE25z1sage4SYFLCCrMi9.jpg",
    release_date: "2019-12-25",
    title: "1917",
    video: false,
    vote_average: 7.993,
    vote_count: 11914,
  },
  {
    adult: false,
    backdrop_path: "/fgffluhvdOv79SkYaKrfRA0xkf4.jpg",
    genre_ids: [18],
    id: 334543,
    original_language: "en",
    original_title: "Lion",
    overview:
      "A five-year-old Indian boy gets lost on the streets of Calcutta, thousands of kilometers from home. He survives many challenges before being adopted by a couple in Australia; 25 years later, he sets out to find his lost family.",
    popularity: 39.493,
    poster_path: "/iBGRbLvg6kVc7wbS8wDdVHq6otm.jpg",
    release_date: "2016-11-24",
    title: "Lion",
    video: false,
    vote_average: 8.073,
    vote_count: 6381,
  },
  {
    adult: false,
    backdrop_path: "/DztBnZaqmla2sGUW9s8AyOmskT.jpg",
    genre_ids: [18],
    id: 14,
    original_language: "en",
    original_title: "American Beauty",
    overview:
      "Lester Burnham, a depressed suburban father in a mid-life crisis, decides to turn his hectic life around after developing an infatuation with his daughter's attractive friend.",
    popularity: 234.507,
    poster_path: "/wby9315QzVKdW9BonAefg8jGTTb.jpg",
    release_date: "1999-09-15",
    title: "American Beauty",
    video: false,
    vote_average: 8.019,
    vote_count: 11687,
  },
  {
    adult: false,
    backdrop_path: "/y6JA85N8DvoonwqDGWlgkr1jnU.jpg",
    genre_ids: [18, 10751],
    id: 28178,
    original_language: "en",
    original_title: "Hachi: A Dog's Tale",
    overview:
      "A drama based on the true story of a college professor's bond with the abandoned dog he takes into his home.",
    popularity: 69.907,
    poster_path: "/lsy3aEsEfYIHdLRk4dontZ4s85h.jpg",
    release_date: "2009-06-08",
    title: "Hachi: A Dog's Tale",
    video: false,
    vote_average: 8.004,
    vote_count: 6465,
  },
  {
    adult: false,
    backdrop_path: "/3RFmTz5h2UuFWEV4oH00XICBR9y.jpg",
    genre_ids: [18, 53, 80],
    id: 146233,
    original_language: "en",
    original_title: "Prisoners",
    overview:
      "Keller Dover is facing a parent’s worst nightmare: his young daughter and her friend have gone missing. Heading the investigation, Detective Loki arrests the only suspect – the driver of an RV on which the girls had been playing – but a lack of evidence forces his release. As pressure mounts, Loki’s team pursues multiple leads while a frantic Dover decides he has no choice but to take matters into his own hands.",
    popularity: 113.015,
    poster_path: "/uhviyknTT5cEQXbn6vWIqfM4vGm.jpg",
    release_date: "2013-09-19",
    title: "Prisoners",
    video: false,
    vote_average: 8.1,
    vote_count: 11299,
  },
  {
    adult: false,
    backdrop_path: "/xJHokMbljvjADYdit5fK5VQsXEG.jpg",
    genre_ids: [12, 18, 878],
    id: 157336,
    original_language: "en",
    original_title: "Interstellar",
    overview:
      "The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.",
    popularity: 425.282,
    poster_path: "/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    release_date: "2014-11-05",
    title: "Interstellar",
    video: false,
    vote_average: 8.434,
    vote_count: 34265,
  },
  {
    adult: false,
    backdrop_path: "/6MmYsaK6poR8f4R8jsBnJBU5tfd.jpg",
    genre_ids: [18, 35],
    id: 400928,
    original_language: "en",
    original_title: "Gifted",
    overview:
      "Frank, a single man raising his child prodigy niece Mary, is drawn into a custody battle with his mother.",
    popularity: 358.788,
    poster_path: "/7YB2YrMwIm1g8FyZtlvmVDfRnAT.jpg",
    release_date: "2017-04-07",
    title: "Gifted",
    video: false,
    vote_average: 8,
    vote_count: 5208,
  },
  {
    adult: false,
    backdrop_path: "/sw7mordbZxgITU877yTpZCud90M.jpg",
    genre_ids: [18, 80],
    id: 769,
    original_language: "en",
    original_title: "GoodFellas",
    overview:
      "The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbourhood gangsters at an early age and climbs the ranks of a Mafia family under the guidance of Jimmy Conway.",
    popularity: 230.956,
    poster_path: "/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg",
    release_date: "1990-09-12",
    title: "GoodFellas",
    video: false,
    vote_average: 8.465,
    vote_count: 12365,
  },
  {
    adult: false,
    backdrop_path: "/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg",
    genre_ids: [12, 878, 28],
    id: 299534,
    original_language: "en",
    original_title: "Avengers: Endgame",
    overview:
      "After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos' actions and restore order to the universe once and for all, no matter what consequences may be in store.",
    popularity: 274.214,
    poster_path: "/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
    release_date: "2019-04-24",
    title: "Avengers: Endgame",
    video: false,
    vote_average: 8.255,
    vote_count: 24832,
  },
  {
    adult: false,
    backdrop_path: "/hZkgoQYus5vegHoetLkCJzb17zJ.jpg",
    genre_ids: [18],
    id: 550,
    original_language: "en",
    original_title: "Fight Club",
    overview:
      'A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy. Their concept catches on, with underground "fight clubs" forming in every town, until an eccentric gets in the way and ignites an out-of-control spiral toward oblivion.',
    popularity: 269.23,
    poster_path: "/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg",
    release_date: "1999-10-15",
    title: "Fight Club",
    video: false,
    vote_average: 8.441,
    vote_count: 28468,
  },
  {
    adult: false,
    backdrop_path: "/tJRToZBfb52NhF6SMGAe0bWQc6z.jpg",
    genre_ids: [18],
    id: 207,
    original_language: "en",
    original_title: "Dead Poets Society",
    overview:
      "At an elite, old-fashioned boarding school in New England, a passionate English teacher inspires his students to rebel against convention and seize the potential of every day, courting the disdain of the stern headmaster.",
    popularity: 67.263,
    poster_path: "/hmGAF5NDoYB6S39UONevjHCESOI.jpg",
    release_date: "1989-06-02",
    title: "Dead Poets Society",
    video: false,
    vote_average: 8.314,
    vote_count: 10797,
  },
  null,
  {
    adult: false,
    backdrop_path: "/qdIMHd4sEfJSckfVJfKQvisL02a.jpg",
    genre_ids: [35, 18, 10749],
    id: 13,
    original_language: "en",
    original_title: "Forrest Gump",
    overview:
      "A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.",
    popularity: 206.804,
    poster_path: "/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg",
    release_date: "1994-06-23",
    title: "Forrest Gump",
    video: false,
    vote_average: 8.475,
    vote_count: 26566,
  },
  {
    adult: false,
    backdrop_path: "/h3weAFgg06GqchI2xDfufBgSFTj.jpg",
    genre_ids: [18],
    id: 600354,
    original_language: "en",
    original_title: "The Father",
    overview:
      "A man refuses all assistance from his daughter as he ages and, as he tries to make sense of his changing circumstances, he begins to doubt his loved ones, his own mind and even the fabric of his reality.",
    popularity: 72.212,
    poster_path: "/pr3bEQ517uMb5loLvjFQi8uLAsp.jpg",
    release_date: "2020-12-23",
    title: "The Father",
    video: false,
    vote_average: 8.129,
    vote_count: 3014,
  },
  {
    adult: false,
    backdrop_path: "/fK5ssgvtI43z19FoWigdlqgpLRE.jpg",
    genre_ids: [16, 10751, 878],
    id: 10681,
    original_language: "en",
    original_title: "WALL·E",
    overview:
      "In the distant future, Earth has become a desolate wasteland, abandoned by humanity and overrun by mountains of trash. Amidst the rubble, a small, lovable robot named WALL-E spends his days tirelessly cleaning up the mess. But when a sleek, high-tech robot named EVE arrives on a mission to search for signs of life, WALL-E is immediately smitten. Together, they embark on a journey across the cosmos.",
    popularity: 100.327,
    poster_path: "/hbhFnRzzg6ZDmm8YAmxBnQpQIPh.jpg",
    release_date: "2008-06-22",
    title: "WALL·E",
    video: false,
    vote_average: 8.088,
    vote_count: 18179,
  },
  {
    adult: false,
    backdrop_path: "/wmsePXV2z1b6ecXuKKrFbG0Q92P.jpg",
    genre_ids: [18],
    id: 13223,
    original_language: "en",
    original_title: "Gran Torino",
    overview:
      "Disgruntled Korean War veteran Walt Kowalski sets out to reform his neighbor, Thao Lor, a Hmong teenager who tried to steal Kowalski's prized possession: a 1972 Gran Torino.",
    popularity: 47.581,
    poster_path: "/zUybYvxWdAJy5hhYovsXtHSWI1l.jpg",
    release_date: "2008-12-12",
    title: "Gran Torino",
    video: false,
    vote_average: 7.993,
    vote_count: 10382,
  },
  {
    adult: false,
    backdrop_path: "/6WRrGYalXXveItfpnipYdayFkQB.jpg",
    genre_ids: [18, 53, 80],
    id: 1422,
    original_language: "en",
    original_title: "The Departed",
    overview:
      "To take down South Boston's Irish Mafia, the police send in one of their own to infiltrate the underworld, not realizing the syndicate has done likewise. While an undercover cop curries favor with the mob kingpin, a career criminal rises through the police ranks. But both sides soon discover there's a mole among them.",
    popularity: 196.62,
    poster_path: "/nT97ifVT2J1yMQmeq20Qblg61T.jpg",
    release_date: "2006-10-04",
    title: "The Departed",
    video: false,
    vote_average: 8.168,
    vote_count: 14395,
  },
  {
    adult: false,
    backdrop_path: "/5vPW6MPAyCFd84FEQQgtPDmVDPQ.jpg",
    genre_ids: [35, 18],
    id: 120467,
    original_language: "en",
    original_title: "The Grand Budapest Hotel",
    overview:
      "The Grand Budapest Hotel tells of a legendary concierge at a famous European hotel between the wars and his friendship with a young employee who becomes his trusted protégé. The story involves the theft and recovery of a priceless Renaissance painting, the battle for an enormous family fortune and the slow and then sudden upheavals that transformed Europe during the first half of the 20th century.",
    popularity: 64.859,
    poster_path: "/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg",
    release_date: "2014-02-26",
    title: "The Grand Budapest Hotel",
    video: false,
    vote_average: 8.05,
    vote_count: 14353,
  },
  {
    adult: false,
    backdrop_path: "/aCHn2TXYJfzPXQKA6r9mKPbMlUB.jpg",
    genre_ids: [35, 18],
    id: 37165,
    original_language: "en",
    original_title: "The Truman Show",
    overview:
      "Truman Burbank is the star of The Truman Show, a 24-hour-a-day reality TV show that broadcasts every aspect of his life without his knowledge. His entire life has been an unending soap opera for consumption by the rest of the world. And everyone he knows, including his wife and his best friend, is really an actor, paid to be part of his life.",
    popularity: 71.921,
    poster_path: "/vuza0WqY239yBXOadKlGwJsZJFE.jpg",
    release_date: "1998-06-04",
    title: "The Truman Show",
    video: false,
    vote_average: 8.14,
    vote_count: 17677,
  },
  {
    adult: false,
    backdrop_path: "/8LRcCJjbQI552BMCuGgYqph8USS.jpg",
    genre_ids: [18],
    id: 7345,
    original_language: "en",
    original_title: "There Will Be Blood",
    overview:
      "Ruthless silver miner, turned oil prospector, Daniel Plainview, moves to oil-rich California. Using his son to project a trustworthy, family-man image, Plainview cons local landowners into selling him their valuable properties for a pittance. However, local preacher Eli Sunday suspects Plainview's motives and intentions, starting a slow-burning feud that threatens both their lives.",
    popularity: 65.836,
    poster_path: "/fa0RDkAlCec0STeMNAhPaF89q6U.jpg",
    release_date: "2007-12-26",
    title: "There Will Be Blood",
    video: false,
    vote_average: 8.083,
    vote_count: 6336,
  },
  {
    adult: false,
    backdrop_path: "/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg",
    genre_ids: [53, 80],
    id: 680,
    original_language: "en",
    original_title: "Pulp Fiction",
    overview:
      "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
    popularity: 382.327,
    poster_path: "/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
    release_date: "1994-09-10",
    title: "Pulp Fiction",
    video: false,
    vote_average: 8.489,
    vote_count: 27040,
  },
  {
    adult: false,
    backdrop_path: "/4I14RDX6gZPpXkHmbcqvAKpn3Dw.jpg",
    genre_ids: [28, 18, 12],
    id: 98,
    original_language: "en",
    original_title: "Gladiator",
    overview:
      "In the year 180, the death of emperor Marcus Aurelius throws the Roman Empire into chaos.  Maximus is one of the Roman army's most capable and trusted generals and a key advisor to the emperor.  As Marcus' devious son Commodus ascends to the throne, Maximus is set to be executed.  He escapes, but is captured by slave traders.  Renamed Spaniard and forced to become a gladiator, Maximus must battle to the death with other men for the amusement of paying audiences.",
    popularity: 139.288,
    poster_path: "/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg",
    release_date: "2000-05-04",
    title: "Gladiator",
    video: false,
    vote_average: 8.216,
    vote_count: 17805,
  },
  {
    adult: false,
    backdrop_path: "/2W9HjAYWNug5RwyrEtrneXeL94Z.jpg",
    genre_ids: [80, 18, 36],
    id: 524,
    original_language: "en",
    original_title: "Casino",
    overview:
      'In early-1970s Las Vegas, Sam "Ace" Rothstein gets tapped by his bosses to head the Tangiers Casino. At first, he\'s a great success in the job, but over the years, problems with his loose-cannon enforcer Nicky Santoro, his ex-hustler wife Ginger, her con-artist ex Lester Diamond and a handful of corrupt politicians put Sam in ever-increasing danger.',
    popularity: 61.972,
    poster_path: "/4TS5O1IP42bY2BvgMxL156EENy.jpg",
    release_date: "1995-11-22",
    title: "Casino",
    video: false,
    vote_average: 8.011,
    vote_count: 5577,
  },
  {
    adult: false,
    backdrop_path: "/r9leYNa8nTRCceZrZhP1DXkgKVb.jpg",
    genre_ids: [27, 9648, 878],
    id: 1091,
    original_language: "en",
    original_title: "The Thing",
    overview:
      "In the winter of 1982, a twelve-man research team at a remote Antarctic research station discovers an alien buried in the snow for over 100,000 years. Soon unfrozen, the form-changing creature wreaks havoc, creates terror... and becomes one of them.",
    popularity: 183.679,
    poster_path: "/tzGY49kseSE9QAKk47uuDGwnSCu.jpg",
    release_date: "1982-06-25",
    title: "The Thing",
    video: false,
    vote_average: 8.059,
    vote_count: 6624,
  },
  {
    adult: false,
    backdrop_path: "/2Xe9lISpwXKhvKiHttbFfVRERQX.jpg",
    genre_ids: [18, 36],
    id: 490132,
    original_language: "en",
    original_title: "Green Book",
    overview:
      "Tony Lip, a bouncer in 1962, is hired to drive pianist Don Shirley on a tour through the Deep South in the days when African Americans, forced to find alternate accommodations and services due to segregation laws below the Mason-Dixon Line, relied on a guide called The Negro Motorist Green Book.",
    popularity: 373.247,
    poster_path: "/7BsvSuDQuoqhWmU2fL7W2GOcZHU.jpg",
    release_date: "2018-11-16",
    title: "Green Book",
    video: false,
    vote_average: 8.244,
    vote_count: 11155,
  },
  {
    adult: false,
    backdrop_path: "/pNHv41t8Im8wlwgdzMK9I8WpuBZ.jpg",
    genre_ids: [18, 36, 10752],
    id: 857,
    original_language: "en",
    original_title: "Saving Private Ryan",
    overview:
      "As U.S. troops storm the beaches of Normandy, three brothers lie dead on the battlefield, with a fourth trapped behind enemy lines. Ranger captain John Miller and seven men are tasked with penetrating German-held territory and bringing the boy home.",
    popularity: 108.919,
    poster_path: "/uqx37cS8cpHg8U35f9U5IBlrCV3.jpg",
    release_date: "1998-07-24",
    title: "Saving Private Ryan",
    video: false,
    vote_average: 8.2,
    vote_count: 15273,
  },
  {
    adult: false,
    backdrop_path: "/rfkIeCaIHhN3K5wjJJqKmfUjYp8.jpg",
    genre_ids: [18, 36],
    id: 381284,
    original_language: "en",
    original_title: "Hidden Figures",
    overview:
      "The untold story of Katherine G. Johnson, Dorothy Vaughan and Mary Jackson – brilliant African-American women working at NASA and serving as the brains behind one of the greatest operations in history – the launch of astronaut John Glenn into orbit. The visionary trio crossed all gender and race lines to inspire generations to dream big.",
    popularity: 79.351,
    poster_path: "/9lfz2W2uGjyow3am00rsPJ8iOyq.jpg",
    release_date: "2016-12-10",
    title: "Hidden Figures",
    video: false,
    vote_average: 8.058,
    vote_count: 9324,
  },
  {
    adult: false,
    backdrop_path: "/wVcrxnNImPHVvAHEDkyLcQUTf6f.jpg",
    genre_ids: [28, 12, 14],
    id: 791373,
    original_language: "en",
    original_title: "Zack Snyder's Justice League",
    overview:
      "Determined to ensure Superman's ultimate sacrifice was not in vain, Bruce Wayne aligns forces with Diana Prince with plans to recruit a team of metahumans to protect the world from an approaching threat of catastrophic proportions.",
    popularity: 150.757,
    poster_path: "/tnAuB8q5vv7Ax9UAEje5Xi4BXik.jpg",
    release_date: "2021-03-18",
    title: "Zack Snyder's Justice League",
    video: false,
    vote_average: 8.2,
    vote_count: 9674,
  },
  {
    adult: false,
    backdrop_path: "/8MksSPtPvqcSDruLdpibPmTP7LY.jpg",
    genre_ids: [28, 53, 878],
    id: 280,
    original_language: "en",
    original_title: "Terminator 2: Judgment Day",
    overview:
      "Set ten years after the events of the original, James Cameron’s classic sci-fi action flick tells the story of a second attempt to get the rid of rebellion leader John Connor, this time targeting the boy himself. However, the rebellion has sent a reprogrammed terminator to protect Connor.",
    popularity: 151.564,
    poster_path: "/5M0j0B18abtBI5gi2RhfjjurTqb.jpg",
    release_date: "1991-07-03",
    title: "Terminator 2: Judgment Day",
    video: false,
    vote_average: 8.114,
    vote_count: 12347,
  },
  {
    adult: false,
    backdrop_path: "/7Wev9JMo6R5XAfz2KDvXb7oPMmy.jpg",
    genre_ids: [9648, 53],
    id: 77,
    original_language: "en",
    original_title: "Memento",
    overview:
      "Leonard Shelby is tracking down the man who raped and murdered his wife. The difficulty of locating his wife's killer, however, is compounded by the fact that he suffers from a rare, untreatable form of short-term memory loss. Although he can recall details of life before his accident, Leonard cannot remember what happened fifteen minutes ago, where he's going, or why.",
    popularity: 64.747,
    poster_path: "/nWtySDlffTfwAa0rSfq61o33ZXV.jpg",
    release_date: "2000-10-11",
    title: "Memento",
    video: false,
    vote_average: 8.184,
    vote_count: 14357,
  },
  {
    adult: false,
    backdrop_path: "/dqK9Hag1054tghRQSqLSfrkvQnA.jpg",
    genre_ids: [18, 28, 80, 53],
    id: 155,
    original_language: "en",
    original_title: "The Dark Knight",
    overview:
      "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.",
    popularity: 165.055,
    poster_path: "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    release_date: "2008-07-16",
    title: "The Dark Knight",
    video: false,
    vote_average: 8.515,
    vote_count: 31891,
  },
  {
    adult: false,
    backdrop_path: "/4i3Amppd6eW5Qkhjv4gdHk3CCoE.jpg",
    genre_ids: [36, 10402, 18],
    id: 279,
    original_language: "en",
    original_title: "Amadeus",
    overview:
      "Wolfgang Amadeus Mozart is a remarkably talented young Viennese composer who unwittingly finds a fierce rival in the disciplined and determined Antonio Salieri. Resenting Mozart for both his hedonistic lifestyle and his undeniable talent, the highly religious Salieri is gradually consumed by his jealousy and becomes obsessed with Mozart's downfall, leading to a devious scheme that has dire consequences for both men.",
    popularity: 74.444,
    poster_path: "/1n5VUlCqgmVax1adxGZm8oCFaKc.jpg",
    release_date: "1984-09-19",
    title: "Amadeus",
    video: false,
    vote_average: 8.037,
    vote_count: 4043,
  },
  {
    adult: false,
    backdrop_path: "/b9YkKJcW3pPaXgMZu9uoT7v9yRB.jpg",
    genre_ids: [16, 28, 12, 878],
    id: 324857,
    original_language: "en",
    original_title: "Spider-Man: Into the Spider-Verse",
    overview:
      'Struggling to find his place in the world while juggling school and family, Brooklyn teenager Miles Morales is unexpectedly bitten by a radioactive spider and develops unfathomable powers just like the one and only Spider-Man. While wrestling with the implications of his new abilities, Miles discovers a super collider created by the madman Wilson "Kingpin" Fisk, causing others from across the Spider-Verse to be inadvertently transported to his dimension.',
    popularity: 146.977,
    poster_path: "/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg",
    release_date: "2018-12-06",
    title: "Spider-Man: Into the Spider-Verse",
    video: false,
    vote_average: 8.405,
    vote_count: 14969,
  },
  {
    adult: false,
    backdrop_path: "/jz9Kep0xWjiA6QDHSsd43ASxNfj.jpg",
    genre_ids: [878, 18, 10749],
    id: 38,
    original_language: "en",
    original_title: "Eternal Sunshine of the Spotless Mind",
    overview:
      "Joel Barish, heartbroken that his girlfriend underwent a procedure to erase him from her memory, decides to do the same. However, as he watches his memories of her fade away, he realises that he still loves her, and may be too late to correct his mistake.",
    popularity: 89.13,
    poster_path: "/5MwkWH9tYHv3mV9OdYTMR5qreIz.jpg",
    release_date: "2004-03-19",
    title: "Eternal Sunshine of the Spotless Mind",
    video: false,
    vote_average: 8.097,
    vote_count: 14382,
  },
  {
    adult: false,
    backdrop_path: "/7S7PE3vK9Eh5uzCYBDGk5qTJeYW.jpg",
    genre_ids: [18, 80, 53],
    id: 629,
    original_language: "en",
    original_title: "The Usual Suspects",
    overview:
      "Held in an L.A. interrogation room, Verbal Kint attempts to convince the feds that a mythic crime lord, Keyser Soze, not only exists, but was also responsible for drawing him and his four partners into a multi-million dollar heist that ended with an explosion in San Pedro harbor – leaving few survivors. Verbal lures his interrogators with an incredible story of the crime lord's almost supernatural prowess.",
    popularity: 57.556,
    poster_path: "/rWbsxdwF9qQzpTPCLmDfVnVqTK1.jpg",
    release_date: "1995-07-19",
    title: "The Usual Suspects",
    video: false,
    vote_average: 8.188,
    vote_count: 10036,
  },
  {
    adult: false,
    backdrop_path: "/7Nwnmyzrtd0FkcRyPqmdzTPppQa.jpg",
    genre_ids: [80, 18, 35],
    id: 106646,
    original_language: "en",
    original_title: "The Wolf of Wall Street",
    overview:
      "A New York stockbroker refuses to cooperate in a large securities fraud case involving corruption on Wall Street, corporate banking world and mob infiltration. Based on Jordan Belfort's autobiography.",
    popularity: 122.436,
    poster_path: "/34m2tygAYBGqA9MXKhRDtzYd4MR.jpg",
    release_date: "2013-12-25",
    title: "The Wolf of Wall Street",
    video: false,
    vote_average: 8,
    vote_count: 23207,
  },
  {
    adult: false,
    backdrop_path: "/hKpzq3U7X1C1lqnYh0WQwlPyxO5.jpg",
    genre_ids: [18, 36],
    id: 1955,
    original_language: "en",
    original_title: "The Elephant Man",
    overview:
      'A Victorian surgeon rescues a heavily disfigured man being mistreated by his "owner" as a side-show freak. Behind his monstrous façade, there is revealed a person of great intelligence and sensitivity. Based on the true story of Joseph Merrick (called John Merrick in the film), a severely deformed man in 19th century London.',
    popularity: 29.364,
    poster_path: "/3SInR81qnXjY7Or5qXyiQLmWfEh.jpg",
    release_date: "1980-10-09",
    title: "The Elephant Man",
    video: false,
    vote_average: 8,
    vote_count: 3346,
  },
  {
    adult: false,
    backdrop_path: "/jqFjgNnxpXIXWuPsyfqmcLXRo9p.jpg",
    genre_ids: [80, 53],
    id: 500,
    original_language: "en",
    original_title: "Reservoir Dogs",
    overview:
      "A botched robbery indicates a police informant, and the pressure mounts in the aftermath at a warehouse. Crime begets violence as the survivors -- veteran Mr. White, newcomer Mr. Orange, psychopathic parolee Mr. Blonde, bickering weasel Mr. Pink and Nice Guy Eddie -- unravel.",
    popularity: 125.471,
    poster_path: "/xi8Iu6qyTfyZVDVy60raIOYJJmk.jpg",
    release_date: "1992-09-02",
    title: "Reservoir Dogs",
    video: false,
    vote_average: 8.129,
    vote_count: 13855,
  },
  {
    adult: false,
    backdrop_path: "/w6Fs4bIje1naeILo9KwAc1Y6bvP.jpg",
    genre_ids: [18, 37],
    id: 68718,
    original_language: "en",
    original_title: "Django Unchained",
    overview:
      "With the help of a German bounty hunter, a freed slave sets out to rescue his wife from a brutal Mississippi plantation owner.",
    popularity: 221.445,
    poster_path: "/bV0rWoiRo7pHUTQkh6Oio6irlXO.jpg",
    release_date: "2012-12-25",
    title: "Django Unchained",
    video: false,
    vote_average: 8.2,
    vote_count: 25539,
  },
];
